sudo: required
services: docker
language: generic

script:
    - ./pipe.sh

    #- docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
    #- docker push cyberdojofoundation/csharp_nunit
    #- trigger dependent repos

