
version: '2'

services:
  runner_client:
    user: nobody
    image: cyberdojo/language_tester
    command: [ "foreman", "start", "-d", "/app" ]
    container_name: runner_client
    ports: [ "4568:4568" ]
    volumes:
      - ./start_point:/app/start_point:ro
      - ./traffic_lights:/app/traffic_lights:ro

  runner_server:
    user: root
    image: cyberdojo/runner:${DOCKER_VERSION}
    command: [ "foreman", "start", "-d", "/app" ]
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    container_name: runner_server
    ports: [ "4567:4567" ]

