
version: '2'

services:
  runner_client:
    user: nobody
    image: cyberdojo/language_tester
    container_name: runner_client
    ports: [ "4558:4558" ]
    volumes:
      - ./start_point:/app/start_point:ro
      - ./traffic_lights:/app/traffic_lights:ro

  runner_server:
    user: root
    image: cyberdojo/runner:${DOCKER_VERSION}
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    container_name: runner_server
    ports: [ "4557:4557" ]
